---
name: add_timezone_to_web_operations
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/64084
rollout_issue_url: https://gitlab.com/gitlab-org/gitaly/-/issues/3655
milestone: '14.1'
type: development
group: group::gitaly
default_enabled: false
