---
name: archive_rate_limit
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/25750
rollout_issue_url: 
milestone: '12.9'
type: development
group: group::source code
default_enabled: false
