---
name: async_commit_diff_files
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/38450
rollout_issue_url: 
milestone: '13.3'
type: development
group: group::source code
default_enabled: false
