---
name: auto_devops_banner_disabled
introduced_by_url: https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/14218
rollout_issue_url: 
milestone: '10.0'
type: development
group: group::pipeline execution
default_enabled: false
