---
name: automated_email_provision
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/75872
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/348317
milestone: '14.6'
type: development
group: group::license
default_enabled: false
