---
name: block_external_fork_network_mirrors
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/60735
rollout_issue_url: 
milestone: '14.0'
type: development
group: group::source code
default_enabled: true
