---
name: board_multi_select
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/61955
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/331189
milestone: '14.0'
type: development
group: group::product planning
default_enabled: false
