---
name: bulk_import_projects
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/68873
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/339941
milestone: '14.3'
type: development
group: group::import
default_enabled: false
