---
name: cache_home_panel
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/57031
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/328421
milestone: '13.12'
type: development
group: group::source code
default_enabled: false
