---
name: cached_mr_widget
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/61584
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/330803
milestone: '13.12'
type: development
group: group::code review
default_enabled: false
