---
name: ci_archived_build_trace_checksum
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/70072
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/340737
milestone: '14.4'
type: development
group: group::pipeline execution
default_enabled: false
