---
name: ci_namespace_project_mirrors
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/75517
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/346786
milestone: '14.6'
type: development
group: group::sharding
default_enabled: false
