---
name: ci_skip_persistent_ref_existence_check
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/32391
rollout_issue_url: 
milestone: '13.1'
type: development
group: group::pipeline execution
default_enabled: false
