---
name: ci_validate_job_length
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/73599
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/344665
milestone: '14.5'
type: development
group: group::pipeline authoring
default_enabled: true
