---
name: collect_package_events
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/45802
rollout_issue_url: 
milestone: '13.6'
type: development
group: group::package
default_enabled: false
