---
name: configure_sentry_in_application_settings
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/73381
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/344832
milestone: '14.5'
type: development
group: group::pipeline execution
default_enabled: false
