---
name: custom_emoji
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/37911
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/231317
milestone: '13.6'
type: development
group: group::project management
default_enabled: false
