---
name: debian_group_packages
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/66188
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/336536
milestone: '14.1'
type: development
group: group::package
default_enabled: false
