---
name: diffs_virtual_scrolling
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/60312
rollout_issue_url:
milestone: '13.12'
type: development
group: group::code review
default_enabled: true
