---
name: disable_ssh_key_used_tracking
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54335
rollout_issue_url: https://gitlab.com/gitlab-com/gl-infra/scalability/-/issues/889
milestone: '13.9'
type: development
group: group::source code
default_enabled: false
