---
name: export_reduce_relation_batch_size
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/34057
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/282245
milestone: '13.1'
type: development
group: group::import
default_enabled: false
