---
name: find_tag_via_gitaly
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/70181
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/340899
milestone: '14.3'
type: development
group: group::source code
default_enabled: true
