---
name: forti_authenticator
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/45055
rollout_issue_url: 
milestone: '13.5'
type: development
group: group::access
default_enabled: false
