---
name: forward_deployment_enabled
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/24412
rollout_issue_url: 
milestone: '12.8'
type: development
group: group::release
default_enabled: true
