---
name: geo_snippet_repository_replication
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/38688
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/224168
milestone: '13.4'
type: development
group: group::geo
default_enabled: true
