---
name: gitaly_pack_objects_hook_with_sidechannel
introduced_by_url: https://gitlab.com/gitlab-org/gitaly/-/merge_requests/3758
rollout_issue_url: https://gitlab.com/gitlab-com/gl-infra/scalability/-/issues/1187
milestone: '14.3'
type: development
group: 'team::Scalability'
default_enabled: false
