---
name: gitaly_upload_pack_gitaly_hooks
introduced_by_url:
rollout_issue_url: https://gitlab.com/gitlab-com/gl-infra/scalability/-/issues/807
milestone: '13.9'
type: development
group:
default_enabled: false
