---
name: gitlab_ci_builds_queuing_metrics
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54909
rollout_issue_url: 
milestone: '13.10'
type: development
group: group::pipeline execution
default_enabled: false
