---
name: gitlab_ci_archived_trace_consistent_reads
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/53716
rollout_issue_url: 
milestone: '13.9'
type: development
group: group::pipeline execution
default_enabled: false
