---
name: go_proxy_disable_gomod_validation
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/34338
rollout_issue_url: 
milestone: '13.1'
type: development
group: group::package
default_enabled: false
