---
name: group_export_ndjson
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/29590
rollout_issue_url: 
milestone: '13.0'
type: development
group: group::import
default_enabled: true
