---
name: group_ci_cd_analytics_page
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/49608
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/292601
milestone: '13.8'
type: development
group: group::release
default_enabled: true
