---
name: improved_emoji_picker
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54469
rollout_issue_url:
milestone: '13.9'
type: development
group: group::code review
default_enabled: true
