---
name: incubation_5mp_google_cloud
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/70715
rollout_issue_url:
milestone: '14.3'
type: development
group: group::incubation
default_enabled: false
