---
name: issue_email_participants
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/49264
rollout_issue_url: 
milestone: '13.8'
type: development
group: group::product planning
default_enabled: false
