---
name: iteration_cadences
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54822
rollout_issue_url:
milestone: '13.10'
type: development
group: group::project management
default_enabled: false
