---
name: json_wrapper_legacy_mode
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/30849
rollout_issue_url: 
milestone: '13.0'
type: development
group: group::source code
default_enabled: true
