---
name: lazy_load_commits
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/71633
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/342497
milestone: '14.4'
type: development
group: group::source code
default_enabled: false
