---
name: load_balancing_for_export_workers
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/68153
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/338615
milestone: '14.2'
type: development
group: group::import
default_enabled: false
