---
name: log_import_export_relation_creation
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/27605
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/282245
milestone: '12.10'
type: development
group: group::import
default_enabled: false
