---
name: new_dir_modal
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/71154
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/341675
milestone: '14.4'
type: development
group: group::source code
default_enabled: true
