---
name: paginated_notes
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/34628
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/254987
milestone: '13.2'
type: development
group: group::code review
default_enabled: false
