---
name: phabricator_import
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/13569
rollout_issue_url: https://gitlab.com/groups/gitlab-org/-/epics/1197
milestone: '12.0'
type: development
group: group::import
default_enabled: true
