---
name: project_export_as_ndjson
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/26995
rollout_issue_url: 
milestone: '12.10'
type: development
group: group::import
default_enabled: true
