---
name: repository_tree_gitaly_pagination
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/67509
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/340419
milestone: '14.3'
type: development
group: group::source code
default_enabled: false
