---
name: runner_registration_control
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/61407
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/336087
milestone: '14.1'
type: development
group: group::runner
default_enabled: false
