---
name: search_blobs_language_aggregation
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/71937
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/342621
milestone: '14.4'
type: development
group: group::global search
default_enabled: false
