---
name: security_finding_build_disable_joins
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/72738
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/342380
milestone: '14.4'
type: development
group: group::threat insights
default_enabled: true
