---
name: security_auto_fix
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/30530
rollout_issue_url: 
milestone: '13.0'
type: development
group: group::composition analysis
default_enabled: false
