---
name: track_file_size_over_highlight_limit
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/61273
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/330374
milestone: '13.12'
type: development
group: group::code review
default_enabled: false
