---
name: traversal_ids_btree
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/69535
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/342871
milestone: '14.5'
type: development
group: group::access
default_enabled: false
