---
name: usage_data_i_snippets_show
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/48113
rollout_issue_url:
milestone: '13.7'
type: development
group: group::editor
default_enabled: true
