---
name: usage_data_i_ci_secrets_management_vault_build_created
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/46515
rollout_issue_url: 
milestone: '13.6'
type: development
group: group::configure
default_enabled: true
