---
name: users_expanding_widgets_usage_data
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/57133
rollout_issue_url:
milestone: '13.11'
type: development
group: group::code review
default_enabled: true
