---
name: validate_import_decompressed_archive_size
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/39686
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/282245
milestone: '13.4'
type: development
group: group::import
default_enabled: true
