---
name: vulnerability_location_image_filter
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/69867
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/340915
milestone: '14.4'
type: development
group: group::container security
default_enabled: true
