---
name: workhorse_archive_cache_disabled
introduced_by_url: https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/16325
rollout_issue_url: 
milestone: '10.5'
type: development
group: group::source code
default_enabled: false
