description: "Reset Docker form"
category: default
action: reset_form
label_description: "`docker_container_retention_and_expiration_policies`"
property_description: ""
value_description: ""
extra_properties:
identifiers:
product_section: ops
product_stage: package
product_group: group::package
product_category:
milestone: "12.8"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/23844
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
