description: "Click tab on new namespace welcoming component"
category: default
action: click_tab
label_description: "Panel name"
property_description: ""
value_description: ""
extra_properties:
identifiers:
product_section: dev
product_stage: manage
product_group: group::import
product_category:
milestone: "13.12"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/59452
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
