description: "Click autocomplete option"
category: default
action: click_text
label_description: "`search_autocomplete_suggestion`"
property_description: "Slugged option category"
value_description: "Option index"
extra_properties:
identifiers:
product_section: enablement
product_stage: enablement
product_group: group::global_search
product_category:
milestone: "13.4"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/40822
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
