description: "Click 2FA codes related buttons: copy, download, print..."
category: default
action: click_button
label_description: "Action button name"
property_description: ""
value_description: ""
extra_properties:
identifiers:
product_section: dev
product_stage: manage
product_group: group::compliance
product_category:
milestone: "13.7"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/49510
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
