description: "Copy file path on diffs"
category: default
action: click_copy_file_button
label_description: "`diff_copy_file_path_button`"
property_description: "`diff_copy_file`"
value_description: ""
extra_properties:
identifiers:
product_section: ""
product_stage: ""
product_group: ""
product_category:
milestone:
introduced_by_url:
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
