description: "Type search query"
category: default
action: type_search_query
label_description: "`[dropdown_type]_dropdown_frequent_items_search_input`"
property_description: ""
value_description: ""
extra_properties:
identifiers:
product_section: dev
product_stage: create
product_group: group::editor
product_category:
milestone: "13.7"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/47589
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
