description: "Show \"What's new\" drawer"
category: default
action: click_whats_new_drawer
label_description: "`namespace_id`"
property_description: "ID of namespace"
value_description: ""
extra_properties:
identifiers:
product_section: growth
product_stage: growth
product_group: group::adoption
product_category:
milestone: "13.5"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/42653
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
