description: "Copy Gradle add to source command"
category: default
action: copy_gradle_add_to_source_command
label_description: "`code_instruction`"
property_description: ""
value_description: ""
extra_properties:
identifiers:
product_section: ops
product_stage: package
product_group: group::package
product_category:
milestone: "13.10"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/55738
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
