description: "Copy Kotlin install command"
category: default
action: copy_kotlin_install_command
label_description: "`code_instruction`"
property_description: ""
value_description: ""
extra_properties:
identifiers:
product_section: ops
product_stage: package
product_group: group::package
product_category:
milestone: "13.12"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/60097
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
