description: "Execute toolbar control"
category: default
action: execute_toolbar_control
label_description: "`content_editor`"
property_description: "Content type"
value_description: "Context data: [heading] 3, [heading] 2"
extra_properties:
identifiers:
product_section: dev
product_stage: create
product_group: group::editor
product_category:
milestone: "13.12"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/61065
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
