description: "Click edit reviewer button when inviting members"
category: default
action: click_invite_members
label_description: "`edit_reviewer`"
property_description: ""
value_description: ""
extra_properties:
identifiers:
product_section: growth
product_stage: growth
product_group: group::expansion
product_category:
milestone: "14.0"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/62505
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
