description: "Execute bubble menu control"
category: default
action: execute_bubble_menu_control
label_description: "`content_editor`"
property_description: ""
value_description: ""
extra_properties:
identifiers:
product_section: dev
product_stage: create
product_group: group::editor
product_category:
milestone: "14.2"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/67363
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
