description: "Click edit reviewer button on right sidebar"
category: default
action: click_edit_button
label_description: "`right_sidebar`"
property_description: "`reviewer`"
value_description: ""
extra_properties:
identifiers:
product_section: ""
product_stage: ""
product_group: ""
product_category:
milestone:
introduced_by_url:
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
