description: Delete container repository tags in bulk
category: delete_tag_bulk
action: tag
label_description:
property_description:
value_description:
extra_properties:
identifiers:
product_section: ops
product_stage: package
product_group: group::package
product_category:
milestone: "13.7"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/48617
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
