description: Update secret detection
category: Security::CiConfiguration::SecretDetectionCreateService
action: update
label_description: One of "true", "false"
property_description:
value_description:
extra_properties:
identifiers:
product_section: sec
product_stage: secure
product_group: group::static_analysis
product_category:
milestone: "13.12"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/58230
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
