description: Marketing email campaigns
category: Groups::EmailCampaignsController
action: click
label_description:
property_description:
value_description:
extra_properties:
identifiers:
product_section: growth
product_stage: growth
product_group: group::activation
product_category:
milestone: "13.11"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/56015
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
