description: Delete project container tag
category: API::ProjectContainerRepositories
action: delete_tag
label_description:
property_description:
value_description:
extra_properties:
identifiers:
product_section: ops
product_stage: package
product_group: group::package
product_category:
milestone: "13.5"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/41846
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
