description: Remove Zoom meeting
category: IncidentManagement::ZoomIntegration
action: remove_zoom_meeting
label_description: The string "Issue ID"
property_description:
value_description: ID of the issue
extra_properties:
identifiers:
product_section: ops
product_stage: monitor
product_group: group::monitor
product_category:
milestone: "12.4"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/18620
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
