description: "Click link to create or import a repository"
category: default
action: click_link
label_description: "`Create or import a repository`"
property_description: "`[Growth::Conversion::Experiment::LearnGitLab | Growth::Activation::Experiment::InviteForHelpContinuousOnboarding]`"
value_description: ""
extra_properties:
identifiers:
product_section: growth
product_stage: growth
product_group: group::conversion
product_category:
milestone: "13.12"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/58689
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
