description: "Edit a single file"
category: default
action: click_consolidated_edit
label_description: "`edit`"
property_description: ""
value_description: ""
extra_properties:
identifiers:
product_section: dev
product_stage: create
product_group: group::editor
product_category:
milestone: "14.1"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/64179
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
