description: Enable manual prometheus
category: cluster:services:prometheus
action: enabled_manual_prometheus
label_description:
property_description:
value_description:
extra_properties:
identifiers:
product_section: dev
product_stage: ecosystem
product_group: group::integrations
product_category:
milestone: "14.0"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/62645
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
