description: "Delete package"
category: "`UI:[MavenPackages | NpmPackages | ConanPackages | undefined]`"
action: delete_package
label_description: ""
property_description: ""
value_description: ""
extra_properties:
identifiers:
product_section: dev
product_stage: create
product_group: group::ecosystem
product_category:
milestone: "13.4"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/41668
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
