description: "Click invite members banner"
category: default
action: invite_members_banner_button_clicked
label_description: "`invite_members_banner`"
property_description: ""
value_description: ""
extra_properties:
identifiers:
product_section: growth
product_stage: growth
product_group: group::expansion
product_category:
milestone: "13.4"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/41774
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
