description: "Show Pipeline suggestion on new MRs"
category: default
action: generic
label_description: "`no_pipeline_noticed`"
property_description: "`[admin | maintainer | developer | owner]`"
value_description: ""
extra_properties:
identifiers:
product_section: growth
product_stage: growth
product_group: group::expansion
product_category:
milestone: "13.12"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/35069
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
