---
extends: ../frontend/.eslintrc.yml
settings:
  import/resolver:
    jest:
      jestConfigFile: 'jest.config.integration.js'
rules:
  no-restricted-imports:
    - error
    - fs
globals:
  mockServer: false
