---
data_category: optional
key_path: counts.static_site_editor_merge_requests
description: Count of merge requests created via Static Site Editor
product_section: dev
product_stage: create
product_group: group::editor
product_category: static_site_editor
value_type: number
status: active
time_frame: all
data_source: redis
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
milestone: "<13.9"
