---
data_category: optional
key_path: usage_activity_by_stage.manage.omniauth_providers
description: Number of unique user logins using an OmniAuth provider
product_section: dev
product_stage: manage
product_group: group::access
product_category: authentication_and_authorization
value_type: number
status: active
time_frame: all
data_source: database
distribution:
- ce
tier:
- free
- premium
- ultimate
milestone: "<13.9"
