---
data_category: optional
key_path: usage_activity_by_stage.create.suggestions
description: Count of unique users who create suggestions in merge request comments
product_section: dev
product_stage: create
product_group: group::code review
product_category: code_review
value_type: number
status: active
time_frame: all
data_source: database
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
milestone: "<13.9"
