---
key_path: redis_hll_counters.ci_templates.p_ci_templates_security_dast_api_latest_weekly
description: Weekly counts for DAST API latest CI template
product_section: sec
product_stage: secure
product_group: dynamic_analysis
product_category: dynamic_application_security_testing
value_type: number
status: active
milestone: "14.6"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/73876
time_frame: 7d
data_source: redis_hll
data_category: optional
instrumentation_class: RedisHLLMetric
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
options:
  events:
  - p_ci_templates_security_dast_api_latest
