---
data_category: optional
key_path: usage_activity_by_stage_monthly.manage.group_imports.gitlab_migration
description: Count of groups imported using GitLab Migration
product_section: dev
product_stage: manage
product_group: group::import
product_category: importers
value_type: number
status: active
time_frame: 28d
data_source: database
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
milestone: "<13.9"
