---
name: block_anonymous_global_searches
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/41041
rollout_issue_url:
milestone: '13.4'
type: ops
group: group::global search
default_enabled: false
