---
name: cached_route_lookups
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/57027
rollout_issue_url:
milestone: '13.11'
type: ops
group: group::source code
default_enabled: false
