---
name: ci_trace_log_invalid_chunks
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/44409
rollout_issue_url: 
milestone: '13.5'
type: ops
group: group::pipeline execution
default_enabled: false
