---
name: database_reindexing
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/42705
rollout_issue_url: 
milestone: '13.5'
type: ops
group: group::database
default_enabled: false
