---
name: database_async_index_creation
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/66478
rollout_issue_url:
milestone: '14.2'
type: ops
group: group::database
default_enabled: false
