---
name: execute_batched_migrations_on_schedule
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/51332
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/326241
milestone: '13.11'
type: ops
group: group::database
default_enabled: true
