---
name: explore_pipeline_status
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/51621
rollout_issue_url: 
milestone: '13.8'
type: ops
group: group::source code
default_enabled: false
