---
name: gitlab_sidekiq_enable_semi_reliable_fetcher
introduced_by_url: https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/23854
rollout_issue_url: 
milestone: '11.6'
type: ops
group: group::geo
default_enabled: true
