---
name: gtm_nonce
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/58494
rollout_issue_url:
milestone: '14.6'
type: ops
group: group::product intelligence
default_enabled: false
