---
name: optimize_batched_migrations
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/60133
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/328817
milestone: '13.12'
type: ops
group: group::database
default_enabled: true
