---
name: usage_data_non_sql_metrics
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/57050
rollout_issue_url: 
milestone: '13.11'
type: ops
group: group::product intelligence
default_enabled: false
